# Generated by Django 5.2.4 on 2025-07-30 08:52

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_blog_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.upload_path),
        ),
    ]
